FROM python:3.10.13-bullseye

# Install dependencies for Chrome
RUN apt-get update && apt-get install -y wget gnupg2

# Install Google Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install -y ./google-chrome-stable_current_amd64.deb

# Install ChromeDriver
RUN apt-get install -yqq unzip
RUN wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/100.0.4896.20/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

# Set display port as an environment variable
ENV DISPLAY=:99

# Install Selenium
RUN pip install selenium

WORKDIR /tests
COPY . /tests
CMD ["python", "integration_test.py"]

